export enum Screens {
  HOME_SCREEN = "HOME_SCREEN",
  LOBBY_SCREEN = "LOBBY_SCREEN",
  GAME_SCREEN = "GAME_SCREEN",
  MONSTER_SELECT_SCREEN = "MONSTER_SELECT_SCREEN",
  WAITING_SCREEN = "WAITING_SCREEN",
}
