version: "3.8"

services:
  nginx:
    restart: always
    image: nginx:1-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl.crt:/etc/nginx/ssl/ssl.crt
      - ./ssl.key:/etc/nginx/ssl/ssl.key

  beastly-brawl:
    restart: always
    image: ${BEASTLY_BRAWL_IMAGE}
    expose:
      - 3002
    ports:
      - 3000:3000
      - 3002:3002
    stdin_open: true
    tty: true
