version: "3.8"

services:
  nginx:
    restart: always
    image: nginx:1-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl.crt:/etc/nginx/ssl/ssl.crt
      - ./ssl.key:/etc/nginx/ssl/ssl.key

  beastly-brawl:
    restart: always
    image: ghcr.io/fit3170-beastly-brawl/beastly-brawl:latest
    environment:
      PORT: 3000
      ROOT_URL: https://www.beastlybrawl.app/
      # IDK ABOUT MONGO URL YET
    expose:
      - 3000
    stdin_open: true
    tty: true
