services:
  nginx:
    restart: always
    image: nginx:1-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl.crt:/etc/nginx/ssl/ssl.crt
      - ./ssl.key:/etc/nginx/ssl/ssl.key
  sample-react-app:
    restart: always
    image: ghcr.io/fit3170-beastly-brawl/sample-react-app:latest
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
