name: Prune Droplet Docker Resources

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
    secrets:
      DIGITAL_OCEAN_DROPLET_IP:
        required: true
      DIGITAL_OCEAN_DROPLET_SSH_PRIVATE_KEY:
        required: true
  workflow_dispatch:   # optional, lets you run manually
  schedule:
    # 19:00 UTC ≈ 5:00 AEST (standard time).
    # Adjust to 18:00 UTC during daylight-saving if you need perfect accuracy.
    - cron: '0 19 * * *'

env:
  droplet_user: root
  droplet_name: droplet-bbs-game-server-${{ inputs.env }}

jobs:
  prune:
    name: Prune old Docker images and volumes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Docker prune on droplet
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DIGITAL_OCEAN_DROPLET_IP }}
          username: ${{ env.droplet_user }}
          key: ${{ secrets.DIGITAL_OCEAN_DROPLET_SSH_PRIVATE_KEY }}
          script: |
            echo "=== Running Docker cleanup on $HOSTNAME ==="
            docker system df
            # Remove images older than 7 days that are unused
            docker image prune -af --filter "until=168h"
            # Remove unused volumes older than 7 days
            docker volume prune -f --filter "until=168h"
            docker system df
