name: Test - Docker Cleanup

on:
  workflow_dispatch:
  schedule:
    # Runs every Sunday at 23:55 AEST
    - cron: "55 13 * * 0"

jobs:
  call-prune-template:
    name: Prune old Docker resources (Test)
    uses: ./.github/workflows/docker-cleanup-template.yaml
    with:
      env: test
    secrets:
      DIGITAL_OCEAN_DROPLET_IP: ${{ secrets.DIGITAL_OCEAN_DROPLET_IP_TEST }}
      DIGITAL_OCEAN_DROPLET_SSH_PRIVATE_KEY: ${{ secrets.DIGITAL_OCEAN_DROPLET_SSH_PRIVATE_KEY_TEST }}
