name: Prod - Startup Droplet & Deploy Game

on:
  workflow_dispatch:

jobs:
  call-startup-template:
    name: Startup Droplet & Deploy Game
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/startup-template.yaml
    with:
      env: prod
    secrets:
      DIGITAL_OCEAN_PAT: ${{ secrets.DIGITAL_OCEAN_PAT }}
      DIGITAL_OCEAN_SPACES_ACCESS_KEY_ID: ${{ secrets.DIGITAL_OCEAN_SPACES_ACCESS_KEY_ID }}
      DIGITAL_OCEAN_SPACES_SECRET_KEY: ${{ secrets.DIGITAL_OCEAN_SPACES_SECRET_KEY }}
      DIGITAL_OCEAN_DROPLET_IP: ${{ secrets.DIGITAL_OCEAN_DROPLET_IP_PROD }}
      DIGITAL_OCEAN_DROPLET_SSH_PRIVATE_KEY: ${{ secrets.DIGITAL_OCEAN_DROPLET_SSH_PRIVATE_KEY_PROD }}
      BEASTLYBRAWL_APP_SSL_CERT: ${{ secrets.BEASTLYBRAWL_APP_SSL_CERT_PROD }}
      BEASTLYBRAWL_APP_SSL_KEY: ${{ secrets.BEASTLYBRAWL_APP_SSL_KEY_PROD }}
      GHCR_PACKAGES_TOKEN: ${{ secrets.GHCR_PACKAGES_TOKEN }}
      BEASTLYBRAWL_APP_ROOT_URL: ${{ secrets.BEASTLYBRAWL_APP_ROOT_URL_PROD }}
      MONGO_URL: ${{ secrets.MONGO_URL }}
